/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodaysWorkoutRouteImport } from './routes/todays-workout'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AddVideoRouteImport } from './routes/add-video'
import { Route as IndexRouteImport } from './routes/index'

const TodaysWorkoutRoute = TodaysWorkoutRouteImport.update({
  id: '/todays-workout',
  path: '/todays-workout',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AddVideoRoute = AddVideoRouteImport.update({
  id: '/add-video',
  path: '/add-video',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-video': typeof AddVideoRoute
  '/debug': typeof DebugRoute
  '/plan': typeof PlanRoute
  '/todays-workout': typeof TodaysWorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-video': typeof AddVideoRoute
  '/debug': typeof DebugRoute
  '/plan': typeof PlanRoute
  '/todays-workout': typeof TodaysWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-video': typeof AddVideoRoute
  '/debug': typeof DebugRoute
  '/plan': typeof PlanRoute
  '/todays-workout': typeof TodaysWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-video' | '/debug' | '/plan' | '/todays-workout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-video' | '/debug' | '/plan' | '/todays-workout'
  id: '__root__' | '/' | '/add-video' | '/debug' | '/plan' | '/todays-workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddVideoRoute: typeof AddVideoRoute
  DebugRoute: typeof DebugRoute
  PlanRoute: typeof PlanRoute
  TodaysWorkoutRoute: typeof TodaysWorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todays-workout': {
      id: '/todays-workout'
      path: '/todays-workout'
      fullPath: '/todays-workout'
      preLoaderRoute: typeof TodaysWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-video': {
      id: '/add-video'
      path: '/add-video'
      fullPath: '/add-video'
      preLoaderRoute: typeof AddVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddVideoRoute: AddVideoRoute,
  DebugRoute: DebugRoute,
  PlanRoute: PlanRoute,
  TodaysWorkoutRoute: TodaysWorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
